### ISSUE TITLE
Forum is not working in Firefox

### ISSUE THREAD

**Issue by Tiwalun** [ccc-rustaceans/room-map#1]
Thanks for creating the map!

The forum isn't working for me in Firefox, due to security settings:

![image](https://user-images.githubusercontent.com/859555/102938187-1ad28500-44ac-11eb-99e5-3d795118fc69.png)

**Comment by dns2utf8** [comment]
Hi

You are welcome :) It looks like I can not fix that for now, one would have to do that on the Forum.
Do you have a suggestion for what to link to?
Do you have a project you would like to present?

Cheers, 
Stefan

**Comment by dns2utf8** [comment]
We replaced the broken link with https://engel-simulator.club/

Closing this issue. Cheers,
Stefan
